### PR TITLE
doc cleanup

### PR DESCRIPTION
**Pull request by atotic**

### CODE REVIEW

**Comment by addyosmani** [comment]
Reviewed with minor comments. Thank you for working on the docs, @atotic!

**Comment by atotic** [comment]
Re: @events . That's where I went down the rabbit hole, currently not planned for I/O. Will try to fix that.

Rest of fixes are in.

**Comment by atotic** [comment]
I mean, all fixes are in, but @events are not going to be displayed

**Comment by addyosmani** [comment]
Thanks for the other fixes. We landed a code style fix in master that will require a rebase here. Want me to take care of that, or would you like to?

**Comment by atotic** [comment]
Please, one of these days you guys will have to show me how to do the
rebase magic.

**Pull request merged**
