### PR TITLE
Removed extra apostrophe from example code "results" attrib.

### PR DESCRIPTION
**Pull request by samcarecho**

### CODE REVIEW

**Comment by arthurvr** [comment]
Duplicate of https://github.com/GoogleWebComponents/google-feeds/pull/13.

**Comment by samcarecho** [comment]
I signed the agreement

**Comment by samcarecho** [comment]
@arthurvr not a duplicate, this request adds a second needed change to the example code that #13 does not, the missing mustaches.

**Comment by arthurvr** [comment]
@samcarecho You just added that second fix, so the first one is still duplicated work. Super easy so I don't really care, closed https://github.com/GoogleWebComponents/google-feeds/pull/13.

**Comment by samcarecho** [comment]
ok, thanks. :)

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
